### ISSUE TITLE
Add more samplers

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#115]
Making an overview here, feel free to correct this list!

- [x] Hamiltonian / Riemannian Monte Carlo. See #104
- [ ] Standard metropolis hastings (non adaptive). See #116
- [ ] SMC. See #80, #120
- [ ] ABC. See #96, #56 
- [ ] Particle MC. See #117
- [x] Nested sampling. See #107

**Comment by MichaelClerx** [comment]
As these have their own tickets, we can close this one!
