### ISSUE TITLE
Toy problems / Benchmark problem suite

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#119]
As part of pints, we'd like a bunch of benchmark problems.

Ideally these would be
- simple enough to be solved with scipy (no added dependencies!)
- able to generate their own test data (already guaranteed with ForwardModel class!)
- from a variety of (biological?) domains
- some of them should have 1st and/or 2nd order derivatives

If they meet all those criteria they can go in the toy model module, otherwise in `problems` or perhaps in a newly created `benchmark` directory? (I think the current `problems` dir contains problem we're actively developing and can have all sorts of dependencies etc. that pints proper doesn't have)

List:
- [x] Logistic model
- [ ] A Michaelis-Menten example (how many species?). See #122 
- [x] Keegan-Mines Banana. See #123 #156
- [x] Simplified ion channel from HH. See #124
- [ ] AP model HH (AP output as time series, but later also derived measures). See #126
- [ ] Represselator #227
- [ ] Van der Pol oscillator. See  #142

**Comment by MichaelClerx** [comment]
@martinjrobins @ben18785 @sanmitraghosh @chonlei If anyone has a better list from the meeting please update the comment above!

**Comment by sanmitraghosh** [comment]
I have assigned this to me. I'll create all the required benchmark problems from systems biology, ecology, epidemiology and synthetic biology. I'll be using scipy odeint for these.

**Comment by MichaelClerx** [comment]
Ok! I can do #124 based on some code I already sent Ben

**Comment by MichaelClerx** [comment]
Closing this, as all points now have their own ticket
