### ISSUE TITLE
Software priorities for paper

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#321]
Hi all!

Just talking to @ben18785 about the things we really need to do for the paper. Thought it'd be good to make an overview ticket.

# MCMC Methods
* [x] Metropolis #253 
* [x] Adaptive covariance #4 
* [x] Diff ev. #149 #189 
* [x] Emcee hammer ~#148~ ~#184~ ~#225~ #281 (ticket) #319 (PR) #320 (interface) (@MichaelClerx @ben18785 ) --> Almost there
* [x] Population #186 
* [x] HMC #104 (@ben18785 @MichaelClerx ) --> Nearly there
* [x] ~NUTS~ (No from Ben & Sanmitra)
* [x] Dream #219 (@MichaelClerx)
* [ ] MALA #294 --> Can be adapted from HMC quite easily (we think)

# Nested methods
* [ ] Nested sampling #107 (@MichaelClerx @ben18785 ) --> Needs ask-tell and notebooks
* [ ] Ellipsoid nested sampling #107 (@MichaelClerx @ben18785 ) --> Needs ask-tell and notebook fix
* [ ] Multinest #282 (@ben18785 ) --> Have study, need to test if it's ok and work into sampler class

# Particle-based methods
* [ ] SMC #120 (@ben18785 ) --> Needs tests, docs, etc.

# Likelihood-free methods
* [x] ABC --> Leaving this for paper 3, Would be a good student project too

# Toy problems #119 
* [x] At least one toy problem with sensitivities #301 
* [x] Logistic #125 
* [x] HH IK
* [x] ~HH AP #126~ AP model #395 (@chonlei)
* [x] Fitzhugh-Nagumo #239 #275 
* [x] Lotke-Volterra #327
* [x] Multi-output Goodwin oscillator #268
* [x] Michaelis-menten #122 (Schnell?) #286
* [x] Banana #123 
* [x] Rosenbrock
* [x] Repressilator #227
* [x] SIR epidemiology model #366

# Features
* [x] Allow non-rectangular boundaries for optimisers #382 (@michaelclerx )
* [x] Allow weighted error measures #397 (@chonlei )

# Functional tests
* [x] Tests for Optimisers #241 (@ben18785 @michaelclerx @martinjrobins )
* [x] Tests for MCMC implementations #181 (@ben18785 @michaelclerx @martinjrobins @sanmitraghosh )
* [x] Infrastructure for functional tests (@martinjrobins @michaelclerx )
* [x] Add (slow) notebook testing to functional tests
* [x] Tests for samplers (adapt MCMC tests)

# Unit tests
* [x] Full tests for diagnostics #173 (@ben18785 )
* [x] Tests for nested sampling #107 (@michaelclerx )
* [x] Full tests for pints.io #347
* [x] Full tests (no output inspection) for `plot.py` #373
* [x] Full tests for pints._optimisers #372
* [x] Full tests for pints._mcmc #374
* [x] All tests should pass on windows #406 (@michaelclerx )

# Documentation
* [x] Notebooks are so slow they keep failing the daily test

# Infra
* [x] Allow `None` returned from MCMC tell, for emcee hammer #320  (@MichaelClerx ) --> Almost there
* [x] Ask/tell where possible for parallelisation, assuming expensive evaluation step ~#132~
* [x] Work out interface to get 1st order sensitivities into Pints ~#43 #299 #343 #344~
* ~Make Pints pip installable (once everything is done)~

# Comparison
* [ ] Matrix for optimisers, matrix for inference #229 (@martinjrobins) --> Up and running
* [x] Bayesian optimisation of hyper parameters (i.e. method settings)(#391 #392 #393)

**Comment by MichaelClerx** [comment]
Questions:

- Should we mention the hierarchical MCMC examples?
- Should we talk about software design, or leave that for a separate paper? (@sanmitraghosh thinks we should write a separate paper about it)

**Comment by martinjrobins** [comment]
I'm guessing we'll need a separate paper for this, to concentrate on it fully, although we should describe the ask-and-tell interface in broad terms and point to a hierarchical MCMC example (which I still need to do) as an example of its utility.

**Comment by MichaelClerx** [comment]
Should we add MALA to the MCMC list for the paper? @sanmitraghosh @ben18785 ?

**Comment by sanmitraghosh** [comment]
Yes MALA, needs `L'(p)` and smMALA, needs `L''(p)`

**Comment by sanmitraghosh** [comment]
@MichaelClerx @martinjrobins @ben18785 I just want to touch up on this point that we should test all single MCMC methods with the FN model and particle ones with GW model. I think this is extremely important at this points or else we might run into the scenario that we have many algorithms (and associated infrastructures) that are not suited for complex ODE models. There is no point in collecting algorithms that can solve the logistic problem. 

I think any algorithms that have not been published (and hopefully cited) with a working non-linear ODE example should be subjected to the aforementioned models FN/GW (performance on the logistic model is absolutely irrelevant for our chosen endeavour) before even implementing on PINTS. This will save us a lot of time and hassle.

**Comment by MichaelClerx** [comment]
Closing this issue now, as it has been replaced by a GitHub Project!
